import org.junit.Test;
import org.apache.log4j.*;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'admin' at '13/01/16 19:41' with Gradle 2.9
 *
 * @author admin, @date 13/01/16 19:41
 */
public class LibraryTest {
	
	static Logger log=Logger.getLogger(LibraryTest.class); 
	
    @Test public void testSomeLibraryMethod() {
		log.info("Returning hello world");
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
