/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '13/01/16 19:41' with Gradle 2.9
 *
 * @author admin, @date 13/01/16 19:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
	
	public static void main( String[] args )
    {
        System.out.println( "Hola Mundo!" );
    }
}
